### ISSUE TITLE
History 

### ISSUE THREAD

**Issue by trust2065** [trust2065/React-projects#5]
As a user, I can record every single cook experience so that I can get full cooking history.

- [x] Design interface of add/view history (include more than one image, date, modified steps and modified ingredients)

- [x] Redesign database (Firebase)

- [x] Modify interface of recipe to accept 'new history' and 'view history'

- [x] Implement function 'new history'

- [x] Implement function 'view history'

**Comment by trust2065** [comment]
User 'remark' field to achieve the demand of recording modified steps/ingredients.
